kind: Pod
apiVersion: v1
metadata:
  name: backup-restore
  labels:
    app.kubernetes.io/name: backup-restore
    app.kubernetes.io/part-of: jira
spec:
  containers:
  - name: backup-app
    image: domaindrivenarchitecture/c4k-jira-backup
    imagePullPolicy: IfNotPresent
    command: ["/entrypoint-start-and-wait.sh"]
    env:
    - name: AWS_DEFAULT_REGION
      value: eu-central-1
    - name: AWS_ACCESS_KEY_ID_FILE
      value: /var/run/secrets/backup-secrets/aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY_FILE
      value: /var/run/secrets/backup-secrets/aws-secret-access-key
    - name: RESTIC_REPOSITORY
      valueFrom:
        configMapKeyRef:
          name: backup-config
          key: restic-repository
    - name: RESTIC_PASSWORD_FILE
      value: /var/run/secrets/backup-secrets/restic-password
    volumeMounts:
    - name: jira-data-volume
      mountPath: /var/backups
    - name: backup-secret-volume
      mountPath: /var/run/secrets/backup-secrets
      readOnly: true
  volumes:
  - name: jira-data-volume
    persistentVolumeClaim:
      claimName: jira-pvc
  - name: backup-secret-volume
    secret:
      secretName: backup-secret
  restartPolicy: OnFailure