apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jira-cert
  namespace: default
spec:
  secretName: jira-secret
  commonName: fqdn
  dnsNames:
  - fqdn
  issuerRef:
    name: staging
    kind: ClusterIssuer