apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
  labels:
    app: jira
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi