apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
  labels:
    app: jira
spec:
  storageClassName: REPLACEME
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: REPLACEME